site_name: Unofficial Addon Documentation
nav:
  - Home: index.md
  - JSON:
      - Power JSON: json/power.md
  - General Types:
    - Data Types: types/data_types.md
    - Power Types: types/power_types.md
  - Action Types:
    - Bi-entity Action Types: types/bientity_action_types.md
    - Block Action Types: types/block_action_types.md
    - Entity Action Types: types/entity_action_types.md
    - Item Action Types: types/item_action_types.md
    - Meta Action Types: types/meta_action_types.md
  - Condition Types:
    - Bi-entity Condition Types: types/bientity_condition_types.md
    - Biome Condition Types: types/biome_condition_types.md
    - Block Condition Types: types/block_condition_types.md
    - Damage Condition Types: types/damage_condition_types.md
    - Entity Condition Types: types/entity_condition_types.md
    - Fluid Condition Types: types/fluid_condition_types.md
    - Item Condition Types: types/item_condition_types.md
    - Meta Condition Types: types/meta_condition_types.md
  - Miscellaneous:
    - Commands: misc/commands.md
    - Item Modifiers: misc/item_modifiers.md
  - Extras:
    - Biome Categories: misc/extras/biome_categories.md
    - Damage Source Names: misc/extras/damage_source_names.md
    - Keybindings: misc/extras/keybindings.md
    - Materials: misc/extras/materials.md
    - Positioned Item Stack Slots: misc/extras/positioned_item_stack_slots.md
    - Space: misc/extras/space.md

theme: readthedocs
markdown_extensions:
    - toc:
        separator: "_"
    - admonition
